[package]
name = "hurry"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
atomic-time = "0.1.5"
blake3 = "1.8.2"
bon = "3.7.1"
cargo_metadata = "0.19.2"
cargo-lock = { version = "10.1.0", features = ["dependency-tree"] }
clap = { version = "4.5", features = ["cargo", "derive", "string"] }
color-eyre = "0.6.5"
derive_more = { version = "2.0.1", features = ["full"] }
enum-assoc = "1.2.4"
filetime = "0.2.25"
flume = "0.11.1"
fslock = "0.2.1"
futures = { version = "0.3.31", features = ["executor"] }
git-version = "0.3.9"
hex = "0.4.3"
homedir = "0.3.4"
itertools = "0.14.0"
lockfile = "0.4.0"
rayon = "1.11.0"
relative-path = { version = "2.0.1", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
strum = { version = "0.27.2", features = ["derive"] }
subenum = "1.1.2"
tap = "1.0.1"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-flame = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing-tree = { version = "0.4.0", features = ["time"] }
walkdir = "2.5.0"
