[package]
name = "hurry"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1.37", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
homedir = "0.3.4"
blake3 = "1.8.2"
rusqlite = { version = "0.35.0", features = ["bundled", "time"] }
rusqlite_migration = { version = "2.1.0", features = ["from-directory"] }
include_dir = "0.7.4"
time = "0.3.41"
walkdir = "2.5.0"
toml = "0.8.22"
