[package]
name = "hypersonic"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
sha2 = "0.10"
anyhow = "1.0"
aws-sdk-s3 = "1.84.0"
bzip2 = "0.5.2"
tar = "0.4"
tokio = { version = "1.37", features = ["full"] }
aws-config = "1.6.2"
aws-smithy-types = "1.3.1"
bytes = "1.10.1"
aws-smithy-runtime-api = "1.8.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
spinners = "4.1.1"
colored = "3.0.0"
git2 = "0.20.2"
