[package]
name = "clients"
version = "0.0.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
bon = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
hex = { workspace = true }
blake3 = { workspace = true }
color-eyre = { workspace = true }
reqwest = { workspace = true, features = ["json", "stream", "rustls-tls", "gzip", "brotli"], optional = true }
tokio = { workspace = true, features = ["full"], optional = true }
tokio-util = { workspace = true, features = ["full"], optional = true }
futures = { workspace = true, optional = true }
url = { workspace = true, optional = true }
async-tar = { workspace = true, optional = true }
piper = { workspace = true, optional = true }
tap = { workspace = true }
tracing = { workspace = true }
flume = { workspace = true, optional = true }
enum-assoc.workspace = true
async-compression = { workspace = true, features = ["tokio", "zstd"], optional = true }
zstd = { workspace = true, optional = true }
http = { workspace = true }
serde_json.workspace = true

[features]
default = []
client = [
    "dep:reqwest",
    "dep:tokio",
    "dep:tokio-util",
    "dep:futures",
    "dep:url",
    "dep:async-tar",
    "dep:piper",
    "dep:flume",
    "dep:async-compression",
    "dep:zstd"
]

[dev-dependencies]
pretty_assertions.workspace = true
