[package]
name = "clients"
version = "0.0.0"
edition = "2024"

[features]
default = []
client = [
    "dep:reqwest",
    "dep:tokio",
    "dep:tokio-util",
    "dep:futures",
    "dep:url",
    "dep:async-tar",
    "dep:piper",
    "dep:flume",
    "dep:async-compression",
    "dep:zstd",
]

[dependencies]
async-compression = { workspace = true, features = ["tokio", "zstd"], optional = true }
async-tar = { workspace = true, optional = true }
blake3 = { workspace = true }
bon = { workspace = true }
color-eyre = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
enum-assoc = { workspace = true }
flume = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
hex = { workspace = true }
http = { workspace = true }
piper = { workspace = true, optional = true }
reqwest = { workspace = true, features = ["json", "stream", "rustls-tls", "gzip", "brotli"], optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tap = { workspace = true }
tokio = { workspace = true, features = ["full"], optional = true }
tokio-util = { workspace = true, features = ["full"], optional = true }
tracing = { workspace = true }
url = { workspace = true, optional = true }
zstd = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints]
workspace = true
