[package]
name = "hurry"
version = "0.1.0"
edition = "2024"

[features]
default = []

[[bench]]
name = "cargo_copy_target"
harness = false
[[bench]]
name = "cargo_cache"
harness = false

[dependencies]
ahash = { workspace = true }
atomic-time = { workspace = true }
blake3 = { workspace = true }
bon = { workspace = true }
cargo_metadata = { workspace = true }
cargo-lock = { workspace = true, features = ["dependency-tree"] }
clap = { workspace = true, features = ["cargo", "derive", "string"] }
color-eyre = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
enum-assoc = { workspace = true }
filetime = { workspace = true }
flume = { workspace = true }
fslock = { workspace = true }
git-version = { workspace = true }
hex = { workspace = true }
homedir = { workspace = true }
itertools = { workspace = true }
lockfile = { workspace = true }
relative-path = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
subenum = { workspace = true }
tap = { workspace = true }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-flame = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-tree = { workspace = true, features = ["time"] }
tokio = { workspace = true, features = ["full"] }
extfn = { workspace = true }
async-walkdir = { workspace = true }
walkdir = { workspace = true }
rayon = { workspace = true }
inquire = {workspace = true }
colored = {workspace = true }
location-macros = {workspace = true }
futures = { workspace = true }
tempfile = { workspace = true }
regex = { workspace = true }
jiff = "0.2.15"

[dev-dependencies]
async-walkdir.workspace = true
divan = { workspace = true }
jwalk = { workspace = true }
pretty_assertions = { workspace = true }
test-log = { workspace = true, features = ["trace"] }
xshell = { workspace = true }
