[package]
name = "hurry"
version = "0.0.0"
edition = "2024"

[features]
default = []

[[bench]]
name = "cargo_copy_target"
harness = false
[[bench]]
name = "walkdir"
harness = false

[dependencies]
atomic-time = { workspace = true }
blake3 = { workspace = true }
bon = { workspace = true }
cargo_metadata = { workspace = true }
clap = { workspace = true, features = ["cargo", "derive", "string"] }
color-eyre = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
enum-assoc = { workspace = true }
filetime = { workspace = true }
fslock = { workspace = true }
git-version = { workspace = true }
hex = { workspace = true }
homedir = { workspace = true }
itertools = { workspace = true }
lockfile = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
subenum = { workspace = true }
tap = { workspace = true }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-flame = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-tree = { workspace = true, features = ["time"] }
tokio = { workspace = true, features = ["full"] }
extfn = { workspace = true }
async-walkdir = { workspace = true }
walkdir = { workspace = true }
rayon = { workspace = true }
inquire = {workspace = true }
colored = {workspace = true }
location-macros = {workspace = true }
futures = { workspace = true }
tempfile = { workspace = true }
home = { workspace = true }
jiff = { workspace = true }
const-str = { workspace = true, features = ["std", "all"] }
duplicate = { workspace = true }
paste = { workspace = true }
parse-display = { workspace = true }
lazy-regex = { workspace = true, features = ["regex", "std"] }
reqwest = { workspace = true, features = ["json", "stream", "rustls-tls", "gzip", "brotli"] }
tokio-util = { workspace = true, features = ["full"] }
url = { workspace = true }
flume = { workspace = true }
num_cpus = { workspace = true }
jwalk.workspace = true
uuid = { workspace = true, features = ["v4"] }
indicatif = { workspace = true }
humansize = { workspace = true }
scopeguard = { workspace = true }
dashmap = { workspace = true }
async-tar = { workspace = true }
piper.workspace = true
console = { workspace = true }

[dev-dependencies]
async-walkdir.workspace = true
divan = { workspace = true }
jwalk = { workspace = true }
pretty_assertions = { workspace = true }
simple_test_case.workspace = true
test-log = { workspace = true, features = ["trace"] }
xshell = { workspace = true }
